// Stor bulk-batch: middagar, saser, tillbehor, soppor, sallader, frukost,
// efterratter, snacks, glass, proteiner, baser. ~230 nya recept.
import { bulkSkriv } from './lib/skriv-recept.mjs';

const c = (modul, slug, namn, n, tid_min, taggar, ingred, steg, brod, glukos = 'mycket-lag', portioner = 2) => ({
  modul, slug, namn, n, tid: { prep_min: tid_min, total_min: tid_min },
  forvantad_glukospaverkan: glukos, portioner, taggar, ingredienser: ingred, tillagning: steg, brod,
});

const a = [];

// === MIDDAGAR — Nordisk/svensk husmans (25) ===
a.push(c('middagar', 'kalops-traditionell', 'Klassisk kalops', { netto_kh: 4, fett: 24, protein: 32, kcal: 380 }, 90, ['middag', 'svensk', 'helg', 'gryta'], [{ mangd: 600, enhet: 'g', vara: 'gryt-kött nöt' }, { mangd: 1, enhet: 'st', vara: 'lök, hackad' }, { mangd: 5, enhet: 'st', vara: 'kryddpepparkorn' }, { mangd: 2, enhet: 'st', vara: 'lagerblad' }, { mangd: 5, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt'], [{ namn: 'Bryn', text: 'Kött i smör 5 min.', timer_min: 5 }, 'Lök, kryddor, buljong.', { namn: 'Sjud', text: '75 min lågt.', timer_min: 75 }], 'Svensk klassiker.', 'lag'));
a.push(c('middagar', 'pyttipanna-lchf', 'LCHF-pyttipanna', { netto_kh: 5, fett: 24, protein: 22, kcal: 340 }, 25, ['middag', 'svensk', 'snabb'], [{ mangd: 300, enhet: 'g', vara: 'rotselleri, tärnad' }, { mangd: 200, enhet: 'g', vara: 'kokt skinka, tärnad' }, { mangd: 200, enhet: 'g', vara: 'fläskkorv, tärnad' }, { mangd: 1, enhet: 'st', vara: 'lök, hackad' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt och peppar', 'Stekta ägg och rödbetor till servering'], [{ namn: 'Stek rotselleri', text: 'Smör, 10 min.', timer_min: 10 }, { namn: 'Lök + protein', text: '5 min.', timer_min: 5 }], 'Klassisk husmans utan potatis.', 'lag'));
a.push(c('middagar', 'kassler-bea-blomkalsmos', 'Kassler med bea och blomkålsmos', { netto_kh: 4, fett: 32, protein: 32, kcal: 460 }, 25, ['middag', 'svensk', 'flask'], [{ mangd: 400, enhet: 'g', vara: 'kassler, tjocka skivor' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 400, enhet: 'g', vara: 'blomkål' }, { mangd: 50, enhet: 'g', vara: 'smör (till mos)' }, { mangd: 0.5, enhet: 'dl', vara: 'grädde' }, '1 dl Lohmanders bea'], [{ namn: 'Stek kassler', text: '4 min/sida.', timer_min: 8 }, 'Koka och mosa blomkål.', 'Servera med bea.'], 'Svensk klassiker.', 'lag'));
a.push(c('middagar', 'flaskpannkaka-bacon', 'LCHF-fläskpannkaka', { netto_kh: 4, fett: 32, protein: 22, kcal: 420 }, 35, ['middag', 'svensk', 'agg'], [{ mangd: 200, enhet: 'g', vara: 'bacon, tärnat' }, { mangd: 4, enhet: 'st', vara: 'ägg' }, { mangd: 100, enhet: 'g', vara: 'mandelmjöl' }, { mangd: 3, enhet: 'dl', vara: 'kokosmjölk' }, { mangd: 1, enhet: 'tsk', vara: 'salt' }], ['Stek bacon i ugnsform.', 'Vispa smet, häll över.', { namn: 'Ugn', text: '180°C, 25 min.', timer_min: 25 }], 'Svensk klassiker, LCHF-anpassad.', 'lag'));
a.push(c('middagar', 'biff-rydberg-rotselleri', 'Biff Rydberg med rotselleri', { netto_kh: 4, fett: 32, protein: 30, kcal: 460 }, 25, ['middag', 'svensk', 'helg', 'klassiker'], [{ mangd: 400, enhet: 'g', vara: 'oxstek, i kuber' }, { mangd: 300, enhet: 'g', vara: 'rotselleri, i kuber' }, { mangd: 1, enhet: 'st', vara: 'gul lök' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 4, enhet: 'st', vara: 'äggulor' }, 'Senap, dijon'], ['Stek rotselleri 10 min.', 'Stek lök 5 min.', 'Stek kött snabbt 3 min.', 'Servera separat med äggula och senap.'], 'Klassisk svensk delikatess.', 'lag'));
a.push(c('middagar', 'jansson-utan-potatis', 'Janssons frestelse utan potatis', { netto_kh: 5, fett: 32, protein: 14, kcal: 400 }, 60, ['middag', 'svensk', 'helg', 'gratäng'], [{ mangd: 400, enhet: 'g', vara: 'rotselleri, i strimlor' }, { mangd: 1, enhet: 'st', vara: 'gul lök' }, { mangd: 100, enhet: 'g', vara: 'ansjovis' }, { mangd: 3, enhet: 'dl', vara: 'vispgrädde' }, { mangd: 30, enhet: 'g', vara: 'smör' }], ['Stek rotselleri och lök i smör 10 min.', 'I form: rotselleri, lök, ansjovis i lager.', 'Häll grädde över.', { namn: 'Ugn', text: '200°C, 35 min.', timer_min: 35 }], 'Svensk julbordsklassiker.', 'lag'));
a.push(c('middagar', 'kalvsylta-traditionell', 'Lammgryta med rotsaker', { netto_kh: 5, fett: 28, protein: 32, kcal: 420 }, 90, ['middag', 'lamm', 'gryta', 'helg'], [{ mangd: 600, enhet: 'g', vara: 'lammbog, i bitar' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 200, enhet: 'g', vara: 'rotselleri' }, { mangd: 100, enhet: 'g', vara: 'morot' }, { mangd: 5, enhet: 'dl', vara: 'lammbuljong' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Rosmarin'], [{ namn: 'Bryn lamm', text: '5 min.', timer_min: 5 }, 'Lök + rotsaker, 5 min.', 'Buljong + rosmarin.', { namn: 'Sjud', text: '75 min.', timer_min: 75 }], 'Klassisk lammgryta.', 'lag'));
a.push(c('middagar', 'kotsoppa-svensk', 'Köttsoppa svensk', { netto_kh: 5, fett: 18, protein: 26, kcal: 290 }, 75, ['middag', 'svensk', 'soppa'], [{ mangd: 500, enhet: 'g', vara: 'gryt-kött' }, { mangd: 200, enhet: 'g', vara: 'rotselleri' }, { mangd: 100, enhet: 'g', vara: 'morot' }, { mangd: 1, enhet: 'st', vara: 'purjolök' }, { mangd: 1, enhet: 'liter', vara: 'kötbuljong' }, 'Persilja och salt'], ['Bryn kött 5 min.', 'Rotsaker + buljong.', { namn: 'Sjud', text: '60 min.', timer_min: 60 }], 'Svensk vinterklassiker.', 'lag'));
a.push(c('middagar', 'kycklingbrost-citronsmor-haricots', 'Smörstekt kycklingbröst med haricots verts', { netto_kh: 3, fett: 28, protein: 36, kcal: 420 }, 25, ['middag', 'kyckling'], [{ mangd: 400, enhet: 'g', vara: 'kycklingbröstfilé' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 300, enhet: 'g', vara: 'haricots verts' }, { mangd: 1, enhet: 'st', vara: 'citron' }, 'Salt och peppar'], [{ namn: 'Stek kyckling', text: '5 min/sida.', timer_min: 10 }, 'Stek bönor 5 min.', 'Citronsaft över allt.'], 'Klassisk vardag.', 'mycket-lag'));
a.push(c('middagar', 'lax-i-folie-citron-dill', 'Lax i folie med citron och dill', { netto_kh: 1, fett: 28, protein: 30, kcal: 380 }, 25, ['middag', 'fisk'], [{ mangd: 400, enhet: 'g', vara: 'laxfilé' }, { mangd: 1, enhet: 'st', vara: 'citron' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 2, enhet: 'msk', vara: 'färsk dill' }, 'Salt och peppar'], ['Lax på folie med smör + citron + dill.', { namn: 'Ugn', text: '180°C, 18 min.', timer_min: 18 }], 'Vardag, ren och enkel.', 'mycket-lag'));
a.push(c('middagar', 'torsk-skinka-pesto', 'Torsk med skinka och pesto', { netto_kh: 2, fett: 22, protein: 30, kcal: 360 }, 22, ['middag', 'fisk'], [{ mangd: 400, enhet: 'g', vara: 'torskfilé' }, { mangd: 4, enhet: 'skivor', vara: 'parmaskinka' }, { mangd: 2, enhet: 'msk', vara: 'pesto' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt och peppar'], ['Bred pesto på torsk, vira skinka runt.', { namn: 'Ugn', text: '180°C, 15 min.', timer_min: 15 }], 'Italiensk-skandinavisk fusion.', 'mycket-lag'));
a.push(c('middagar', 'lammrostbiff-rotselleri', 'Lammrostbiff med rotsellerimos', { netto_kh: 4, fett: 30, protein: 32, kcal: 440 }, 75, ['middag', 'lamm', 'helg'], [{ mangd: 600, enhet: 'g', vara: 'lammrostbiff' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 3, enhet: 'msk', vara: 'rosmarin' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 400, enhet: 'g', vara: 'rotselleri' }, { mangd: 0.5, enhet: 'dl', vara: 'grädde' }, 'Salt'], [{ namn: 'Marinera', text: '30 min.' }, { namn: 'Ugn', text: '125°C, 50 min.', timer_min: 50 }, 'Vila 10 min.', 'Mosa rotselleri med smör + grädde.'], 'Helgmiddag.', 'lag'));
a.push(c('middagar', 'oxfile-rodvin-blomkalsmos', 'Oxfilé i rödvinssås med blomkålsmos', { netto_kh: 4, fett: 32, protein: 38, kcal: 480 }, 35, ['middag', 'helg', 'notkott'], [{ mangd: 500, enhet: 'g', vara: 'oxfilé' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'dl', vara: 'torrt rödvin' }, { mangd: 2, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 1, enhet: 'dl', vara: 'grädde' }, { mangd: 400, enhet: 'g', vara: 'blomkål' }, 'Salt'], ['Bryn oxfilé 4 min/sida.', 'Vila under folie.', 'Sås: deglaze panna med vin, buljong, grädde, sjud 5 min.', 'Mosa blomkål.'], 'Fransk-svensk klassiker.', 'lag'));
a.push(c('middagar', 'fisk-i-baljvitvinsbuljong', 'Vitfisk i vitvinsbuljong', { netto_kh: 2, fett: 18, protein: 28, kcal: 280 }, 20, ['middag', 'fisk', 'fransk'], [{ mangd: 400, enhet: 'g', vara: 'torskfilé' }, { mangd: 1, enhet: 'dl', vara: 'torrt vitvin' }, { mangd: 2, enhet: 'dl', vara: 'fiskbuljong' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'msk', vara: 'färsk persilja' }, 'Salt'], [{ namn: 'Sjud', text: 'Vin + buljong + smör 5 min.', timer_min: 5 }, { namn: 'Fisk', text: 'Lägg i fisken, sjud 8 min.', timer_min: 8 }], 'Fransk klassiker.', 'mycket-lag'));
a.push(c('middagar', 'kotbullar-grаdde', 'Köttbullar i gräddsås', { netto_kh: 3, fett: 32, protein: 24, kcal: 420 }, 30, ['middag', 'svensk', 'klassiker'], [{ mangd: 500, enhet: 'g', vara: 'nötfärs' }, { mangd: 1, enhet: 'st', vara: 'ägg' }, { mangd: 3, enhet: 'msk', vara: 'mandelmjöl' }, { mangd: 1, enhet: 'st', vara: 'lök, finhackad' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 2, enhet: 'dl', vara: 'grädde' }, { mangd: 1, enhet: 'msk', vara: 'soja' }], ['Forma 16 köttbullar.', { namn: 'Stek', text: '8 min.', timer_min: 8 }, 'Sås: smör + grädde + soja, sjud 5 min.'], 'Svensk klassiker, LCHF.', 'lag'));
a.push(c('middagar', 'flaskfile-aplecidersås', 'Fläskfilé i äppelcidersås', { netto_kh: 4, fett: 26, protein: 32, kcal: 410 }, 25, ['middag', 'flask', 'fransk'], [{ mangd: 500, enhet: 'g', vara: 'fläskfilé' }, { mangd: 1, enhet: 'dl', vara: 'äppelcidervinäger' }, { mangd: 2, enhet: 'dl', vara: 'grädde' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'msk', vara: 'dijonsenap' }, 'Salt och peppar'], [{ namn: 'Stek', text: 'Bryn allsidigt 4 min.', timer_min: 4 }, { namn: 'Ugn', text: '180°C, 12 min.', timer_min: 12 }, 'Sås: deglaze + grädde + senap.'], 'Fransk klassiker.', 'lag'));
a.push(c('middagar', 'kyckling-bacon-svenska', 'Kyckling med bacon och brysselkål', { netto_kh: 4, fett: 30, protein: 32, kcal: 430 }, 35, ['middag', 'kyckling'], [{ mangd: 500, enhet: 'g', vara: 'kycklinglår' }, { mangd: 100, enhet: 'g', vara: 'bacon' }, { mangd: 300, enhet: 'g', vara: 'brysselkål' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt och peppar'], [{ namn: 'Stek bacon', text: '5 min.', timer_min: 5 }, { namn: 'Stek kyckling', text: 'I baconfettet, 8 min/sida.', timer_min: 16 }, 'Brysselkål 8 min.'], 'Vintervardag.', 'lag'));
a.push(c('middagar', 'lammracks-rosmarin-bea', 'Lammracks med rosmarin och bea', { netto_kh: 1, fett: 36, protein: 36, kcal: 480 }, 35, ['middag', 'lamm', 'helg'], [{ mangd: 600, enhet: 'g', vara: 'lammracks' }, { mangd: 3, enhet: 'msk', vara: 'rosmarin' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 30, enhet: 'g', vara: 'smör' }, '1 dl Lohmanders bea', 'Salt'], [{ namn: 'Bryn', text: '4 min/sida.', timer_min: 8 }, { namn: 'Ugn', text: '180°C, 12 min.', timer_min: 12 }, 'Vila 8 min.'], 'Lyx-helgmat.', 'mycket-lag'));
a.push(c('middagar', 'rakor-skagen-modernt', 'Skagenröra modernt', { netto_kh: 3, fett: 26, protein: 22, kcal: 350 }, 15, ['middag', 'svensk', 'fest', 'skaldjur'], [{ mangd: 400, enhet: 'g', vara: 'räkor' }, { mangd: 3, enhet: 'msk', vara: 'majonnäs' }, { mangd: 2, enhet: 'msk', vara: 'crème fraîche' }, { mangd: 2, enhet: 'msk', vara: 'färsk dill' }, { mangd: 1, enhet: 'tsk', vara: 'pepparrot, riven' }, { mangd: 1, enhet: 'st', vara: 'citron' }, '4 skivor fathead-bröd', '4 ägghalvor'], ['Blanda röran.', 'Lägg på fathead, ägg, dill.'], 'Klassisk svensk fest.', 'lag'));
a.push(c('middagar', 'mussel-fond-vitvin', 'Musslor i vitvin med smör', { netto_kh: 3, fett: 22, protein: 22, kcal: 320 }, 20, ['middag', 'fransk', 'skaldjur'], [{ mangd: 1, enhet: 'kg', vara: 'blåmusslor' }, { mangd: 2, enhet: 'dl', vara: 'torrt vitvin' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'msk', vara: 'färsk persilja' }], ['Smör + vitlök 1 min.', 'Vin + musslor, lock, 5 min.', 'Persilja över.'], 'Mules marinière.', 'lag'));
a.push(c('middagar', 'duo-vitfisk-pilgrimsmussla', 'Vitfisk med pilgrimsmusslor', { netto_kh: 1, fett: 24, protein: 28, kcal: 340 }, 18, ['middag', 'fisk', 'helg'], [{ mangd: 200, enhet: 'g', vara: 'torsk eller havsabborre' }, { mangd: 4, enhet: 'st', vara: 'pilgrimsmusslor' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'st', vara: 'citron' }, 'Salt och peppar'], ['Stek torsk i smör 4 min/sida.', 'Stek pilgrimsmusslor 90 sek/sida.', 'Citronsaft.'], 'Lyx-fisk-trio.', 'mycket-lag'));
a.push(c('middagar', 'fyllda-paprikor-kottfars', 'Fyllda paprikor med köttfärs', { netto_kh: 5, fett: 26, protein: 26, kcal: 380 }, 50, ['middag', 'helg'], [{ mangd: 4, enhet: 'st', vara: 'paprikor, urgröpta' }, { mangd: 400, enhet: 'g', vara: 'nötfärs' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 100, enhet: 'g', vara: 'mozzarella' }, { mangd: 1, enhet: 'tsk', vara: 'oregano' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }], ['Stek färs + lök 8 min.', 'Tillsätt tomat + oregano.', 'Fyll paprika, toppa med ost.', { namn: 'Ugn', text: '200°C, 35 min.', timer_min: 35 }], 'Klassiker.', 'lag'));
a.push(c('middagar', 'porchetta-italiensk-style', 'Italiensk porchetta', { netto_kh: 1, fett: 38, protein: 32, kcal: 480 }, 90, ['middag', 'italiensk', 'flask', 'helg'], [{ mangd: 1, enhet: 'kg', vara: 'fläsksida med svål' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 3, enhet: 'msk', vara: 'fänkålsfrö' }, { mangd: 2, enhet: 'msk', vara: 'rosmarin' }, 'Salt och peppar'], ['Massera in kryddor.', { namn: 'Ugn', text: '160°C, 75 min, sen 220°C 15 min för krispighet.', timer_min: 90 }], 'Italiensk fläskklassiker.', 'mycket-lag'));
a.push(c('middagar', 'pasta-zoodles-bolognese', 'Zoodles med bolognese', { netto_kh: 5, fett: 22, protein: 24, kcal: 320 }, 35, ['middag', 'italiensk', 'gronsak'], [{ mangd: 2, enhet: 'st', vara: 'zucchini, spiraliserade' }, { mangd: 400, enhet: 'g', vara: 'nötfärs' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, 'Oregano, basilika'], ['Stek färs + lök 8 min.', 'Tomater + örter, sjud 15 min.', 'Wokra zoodles 2 min.', 'Servera med sås, parmesan över.'], 'Italiensk pasta utan pasta.', 'lag'));

// === MIDDAGAR — Italiensk/medelhav (15) ===
a.push(c('middagar', 'kyckling-piccata', 'Kyckling piccata', { netto_kh: 2, fett: 24, protein: 36, kcal: 380 }, 22, ['middag', 'italiensk', 'kyckling'], [{ mangd: 400, enhet: 'g', vara: 'kycklingbröst, klappade tunna' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'st', vara: 'citron' }, { mangd: 2, enhet: 'msk', vara: 'kapris' }, { mangd: 1, enhet: 'dl', vara: 'kycklingbuljong' }], ['Stek kyckling 4 min/sida.', 'Sås: smör + citron + kapris + buljong.'], 'Italiensk klassiker.', 'mycket-lag'));
a.push(c('middagar', 'lax-italiensk-saltimbocca', 'Lax saltimbocca-style', { netto_kh: 1, fett: 26, protein: 32, kcal: 380 }, 18, ['middag', 'italiensk', 'fisk'], [{ mangd: 400, enhet: 'g', vara: 'lax' }, { mangd: 4, enhet: 'skivor', vara: 'parmaskinka' }, { mangd: 2, enhet: 'st', vara: 'kvistar färsk salvia' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'dl', vara: 'torrt vitvin' }], ['Salvia på lax, vira skinka runt.', 'Stek 4 min/sida.', 'Deglaze med vin.'], 'Italiensk klassiker.', 'mycket-lag'));
a.push(c('middagar', 'osso-bucco-style', 'Osso bucco kalvskank', { netto_kh: 4, fett: 24, protein: 36, kcal: 400 }, 120, ['middag', 'italiensk', 'kalv', 'helg'], [{ mangd: 800, enhet: 'g', vara: 'kalvskank' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 3, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 2, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Gremolata'], ['Bryn kött 5 min.', 'Lök + vitlök + tomat + buljong.', { namn: 'Sjud', text: '110 min lågt.', timer_min: 110 }, 'Toppa med gremolata.'], 'Italiensk klassiker.', 'lag'));
a.push(c('middagar', 'puttanesca-zoodles', 'Zoodles puttanesca', { netto_kh: 5, fett: 22, protein: 12, kcal: 290 }, 25, ['middag', 'italiensk'], [{ mangd: 2, enhet: 'st', vara: 'zucchini, spiraliserade' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 50, enhet: 'g', vara: 'kalamata-oliver' }, { mangd: 2, enhet: 'msk', vara: 'kapris' }, { mangd: 4, enhet: 'st', vara: 'ansjovisfileer' }, { mangd: 3, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'tsk', vara: 'chiliflakes' }], ['Stek vitlök + ansjovis + chili 1 min.', 'Tomat + oliver + kapris, sjud 10 min.', 'Wokra zoodles, vänd in såsen.'], 'Klassisk neapelitansk.', 'lag'));
a.push(c('middagar', 'caprese-baktade-tomater', 'Bakat caprese-fyllda tomater', { netto_kh: 4, fett: 18, protein: 14, kcal: 240 }, 35, ['middag', 'italiensk', 'vegetariskt'], [{ mangd: 4, enhet: 'st', vara: 'stora tomater, urgröpta' }, { mangd: 200, enhet: 'g', vara: 'mozzarella, tärnad' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, 'Färsk basilika', { mangd: 1, enhet: 'msk', vara: 'olivolja' }], ['Fyll tomater med ost.', { namn: 'Ugn', text: '180°C, 25 min.', timer_min: 25 }, 'Basilika över.'], 'Italiensk vegetarisk.', 'lag'));
a.push(c('middagar', 'kalvfile-saltimbocca', 'Kalvfilé saltimbocca', { netto_kh: 1, fett: 22, protein: 36, kcal: 360 }, 20, ['middag', 'italiensk', 'kalv'], [{ mangd: 400, enhet: 'g', vara: 'kalvfilé, klappad tunn' }, { mangd: 4, enhet: 'skivor', vara: 'parmaskinka' }, { mangd: 4, enhet: 'st', vara: 'salvia-blad' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'dl', vara: 'torrt vitvin' }], ['Salvia + skinka på kalv, fäst med tandpetare.', 'Stek 3 min/sida.', 'Deglaze med vin.'], '"Hoppar i munnen" — italiensk.', 'mycket-lag'));
a.push(c('middagar', 'frutti-di-mare-skipped', '', { netto_kh: 0, fett: 0, protein: 0, kcal: 0 }, 0, [], [], [], '')); // skip svamp/musslor diversity already
a.push(c('middagar', 'kyckling-cacciatore', 'Kyckling cacciatore', { netto_kh: 5, fett: 28, protein: 32, kcal: 420 }, 50, ['middag', 'italiensk'], [{ mangd: 600, enhet: 'g', vara: 'kycklinglår' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 1, enhet: 'dl', vara: 'rödvin' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Rosmarin, oregano'], ['Bryn kyckling 6 min.', 'Lök + tomat + vin.', { namn: 'Sjud', text: '40 min.', timer_min: 40 }], 'Italiensk husmans.', 'lag'));
a.push(c('middagar', 'kyckling-marsala', 'Kyckling marsala', { netto_kh: 4, fett: 26, protein: 34, kcal: 400 }, 25, ['middag', 'italiensk', 'kyckling'], [{ mangd: 400, enhet: 'g', vara: 'kycklingbröst' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'dl', vara: 'marsala-vin' }, { mangd: 1, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 1, enhet: 'dl', vara: 'grädde' }], ['Stek kyckling 5 min/sida.', 'Sås: smör + marsala + buljong + grädde.'], 'Italiensk klassiker.', 'lag'));
a.push(c('middagar', 'lammravioli-skipped', '', { netto_kh: 0, fett: 0, protein: 0, kcal: 0 }, 0, [], [], [], '')); // skip pasta
a.push(c('middagar', 'frittata-spenat-feta', 'Spenat-feta-frittata', { netto_kh: 3, fett: 24, protein: 22, kcal: 320 }, 30, ['middag', 'italiensk', 'agg'], [{ mangd: 8, enhet: 'st', vara: 'ägg' }, { mangd: 200, enhet: 'g', vara: 'spenat' }, { mangd: 100, enhet: 'g', vara: 'fetaost' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt och peppar'], ['Stek spenat + lök 5 min.', 'Vispa ägg, häll i, fetaost över.', { namn: 'Ugn', text: '180°C, 20 min.', timer_min: 20 }], 'Italiensk klassiker.', 'mycket-lag'));
a.push(c('middagar', 'oxstek-italiensk-stil', 'Oxstek på italienskt sätt', { netto_kh: 2, fett: 28, protein: 38, kcal: 440 }, 30, ['middag', 'italiensk', 'helg'], [{ mangd: 500, enhet: 'g', vara: 'oxfilé' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 3, enhet: 'msk', vara: 'rosmarin' }, { mangd: 50, enhet: 'g', vara: 'parmesan, flagor' }, 'Rucola till servering'], [{ namn: 'Bryn', text: '4 min/sida.', timer_min: 8 }, 'Ugn 180°C 8 min.', 'Vila, skär, parmesan + rucola.'], 'Tagliata italiensk.', 'mycket-lag'));
a.push(c('middagar', 'lax-pesto-uppskuren', 'Lax i ugn med pesto', { netto_kh: 2, fett: 28, protein: 30, kcal: 400 }, 22, ['middag', 'italiensk', 'fisk'], [{ mangd: 400, enhet: 'g', vara: 'laxfilé' }, { mangd: 3, enhet: 'msk', vara: 'pesto' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, { mangd: 30, enhet: 'g', vara: 'pinjenötter' }], ['Lax på folie, pesto, parmesan, pinjenötter.', { namn: 'Ugn', text: '180°C, 18 min.', timer_min: 18 }], 'Snabb italiensk-modern.', 'mycket-lag'));
a.push(c('middagar', 'romersk-mozzarella-aubergine', 'Romersk aubergine med mozzarella', { netto_kh: 5, fett: 22, protein: 14, kcal: 300 }, 50, ['middag', 'italiensk', 'vegetariskt'], [{ mangd: 2, enhet: 'st', vara: 'auberginer, i skivor' }, { mangd: 200, enhet: 'g', vara: 'mozzarella' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, 'Basilika'], ['Stek aubergine 4 min/sida.', 'Lager: tomat + aubergine + mozzarella x 2.', { namn: 'Ugn', text: '200°C, 25 min.', timer_min: 25 }], 'Aubergine parmigiana.', 'lag'));

// === SASER (40) ===
a.push(c('saser', 'gradde-konjak-pepparsas', 'Pepparsås med konjak', { netto_kh: 2, fett: 22, protein: 2, kcal: 220 }, 12, ['sas', 'klassiker', 'fransk'], [{ mangd: 2, enhet: 'dl', vara: 'vispgrädde' }, { mangd: 2, enhet: 'msk', vara: 'grön peppar i lag' }, { mangd: 1, enhet: 'msk', vara: 'cognac' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt'], ['Krossa peppar.', 'Smör + cognac + flambera.', 'Grädde + peppar, sjud 5 min.'], 'Hemmagjord pepparsås.'));
a.push(c('saser', 'rodvinsas-bea-style', 'Rödvinssås med smör', { netto_kh: 2, fett: 18, protein: 1, kcal: 180 }, 15, ['sas', 'klassiker', 'fransk'], [{ mangd: 1, enhet: 'dl', vara: 'torrt rödvin' }, { mangd: 2, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'st', vara: 'schalottenlök' }], ['Reducera vin + buljong + lök till hälften.', 'Vispa in smör.'], 'Klassisk rödvinssås.'));
a.push(c('saser', 'kallsas-rakor-cocktail', 'Räk-cocktailsås', { netto_kh: 2, fett: 18, protein: 1, kcal: 180 }, 5, ['sas', 'kall'], [{ mangd: 2, enhet: 'msk', vara: 'majonnäs' }, { mangd: 1, enhet: 'msk', vara: 'tomatpuré' }, { mangd: 1, enhet: 'tsk', vara: 'pressad citron' }, { mangd: 1, enhet: 'tsk', vara: 'cognac' }, { mangd: 1, enhet: 'krm', vara: 'cayenne' }], ['Vispa.'], 'Räkcocktail-sås.'));
a.push(c('saser', 'gravlax-sas-senap', 'Hovmästarsås till gravlax', { netto_kh: 3, fett: 22, protein: 2, kcal: 220 }, 5, ['sas', 'kall', 'svensk'], [{ mangd: 3, enhet: 'msk', vara: 'majonnäs' }, { mangd: 2, enhet: 'msk', vara: 'dijonsenap' }, { mangd: 2, enhet: 'msk', vara: 'sukrin gold' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }, { mangd: 2, enhet: 'msk', vara: 'färsk dill' }], ['Vispa allt.'], 'Hovmästarsås LCHF.'));
a.push(c('saser', 'kall-vitloksas', 'Kall vitlökssås', { netto_kh: 1, fett: 16, protein: 2, kcal: 160 }, 5, ['sas', 'kall'], [{ mangd: 1, enhet: 'dl', vara: 'majonnäs' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor, pressade' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }, 'Salt'], ['Vispa.'], 'Snabb vitlöksmajo.'));
a.push(c('saser', 'tartarsas', 'Tartarsås', { netto_kh: 2, fett: 22, protein: 1, kcal: 220 }, 5, ['sas', 'kall'], [{ mangd: 2, enhet: 'dl', vara: 'majonnäs' }, { mangd: 2, enhet: 'msk', vara: 'kapris, finhackade' }, { mangd: 2, enhet: 'msk', vara: 'inlagda gurkor' }, { mangd: 1, enhet: 'msk', vara: 'färsk persilja' }, { mangd: 1, enhet: 'tsk', vara: 'pressad citron' }], ['Blanda allt.'], 'Klassisk fisk-sås.'));
a.push(c('saser', 'rom-sour-cream-sas', 'Sour cream med rom', { netto_kh: 2, fett: 14, protein: 4, kcal: 180 }, 5, ['sas', 'kall', 'lyx'], [{ mangd: 2, enhet: 'dl', vara: 'gräddfil' }, { mangd: 30, enhet: 'g', vara: 'löjrom' }, { mangd: 1, enhet: 'msk', vara: 'färsk dill' }, { mangd: 1, enhet: 'tsk', vara: 'pressad citron' }, 'Salt och peppar'], ['Vispa allt.'], 'Lyx-fisk-sås.'));
a.push(c('saser', 'remoulade-keto', 'Remoulade keto', { netto_kh: 2, fett: 22, protein: 1, kcal: 220 }, 8, ['sas', 'kall'], [{ mangd: 2, enhet: 'dl', vara: 'majonnäs' }, { mangd: 2, enhet: 'msk', vara: 'inlagda gurkor, hackade' }, { mangd: 1, enhet: 'msk', vara: 'kapris, hackade' }, { mangd: 1, enhet: 'msk', vara: 'dijonsenap' }, { mangd: 1, enhet: 'msk', vara: 'persilja' }, { mangd: 1, enhet: 'tsk', vara: 'curry' }], ['Vispa.'], 'Dansk klassiker.'));
a.push(c('saser', 'pesto-grön-pinjenot', 'Klassisk grön pesto', { netto_kh: 1, fett: 28, protein: 6, kcal: 290 }, 8, ['sas', 'italiensk'], [{ mangd: 2, enhet: 'dl', vara: 'färsk basilika' }, { mangd: 50, enhet: 'g', vara: 'pinjenötter' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'dl', vara: 'olivolja' }], ['Mortla eller mixa.'], 'Klassisk pesto.'));
a.push(c('saser', 'rod-pesto-soltorkad-tomat', 'Röd pesto med soltorkad tomat', { netto_kh: 3, fett: 26, protein: 6, kcal: 280 }, 8, ['sas', 'italiensk'], [{ mangd: 50, enhet: 'g', vara: 'soltorkad tomat' }, { mangd: 50, enhet: 'g', vara: 'parmesan' }, { mangd: 30, enhet: 'g', vara: 'pinjenötter' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'dl', vara: 'olivolja' }], ['Mixa.'], 'Röd italiensk variant.'));
a.push(c('saser', 'beurre-blanc', 'Beurre blanc (vitvinsmör)', { netto_kh: 1, fett: 32, protein: 1, kcal: 290 }, 12, ['sas', 'fransk', 'fisk'], [{ mangd: 1, enhet: 'dl', vara: 'torrt vitvin' }, { mangd: 1, enhet: 'msk', vara: 'vitvinsvinäger' }, { mangd: 1, enhet: 'st', vara: 'schalottenlök, finhackad' }, { mangd: 100, enhet: 'g', vara: 'smör, kallt, i tärningar' }], ['Reducera vin + vinäger + lök till 1 msk.', 'Vispa in smör en bit i taget.'], 'Klassisk fransk fisk-sås.'));
a.push(c('saser', 'currysmor', 'Currysmör', { netto_kh: 1, fett: 22, protein: 1, kcal: 200 }, 5, ['sas', 'snabb', 'krydda'], [{ mangd: 100, enhet: 'g', vara: 'smör, rumstempererat' }, { mangd: 1, enhet: 'msk', vara: 'curry-pulver' }, { mangd: 1, enhet: 'tsk', vara: 'pressad citron' }, 'Salt'], ['Rör samman.', 'Forma till "korv" i plastfilm, kyl.'], 'Smaksatt smör.'));
a.push(c('saser', 'vitlokssmor', 'Vitlökssmör', { netto_kh: 1, fett: 22, protein: 1, kcal: 200 }, 5, ['sas', 'snabb'], [{ mangd: 100, enhet: 'g', vara: 'smör' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor, pressade' }, { mangd: 1, enhet: 'msk', vara: 'färsk persilja' }, 'Salt'], ['Rör.'], 'Klassiskt smaksmör.'));
a.push(c('saser', 'chiliflingosmor', 'Chili-flingor-smör', { netto_kh: 1, fett: 22, protein: 1, kcal: 200 }, 5, ['sas', 'het'], [{ mangd: 100, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'tsk', vara: 'chiliflakes' }, { mangd: 1, enhet: 'tsk', vara: 'rökt paprika' }, 'Salt'], ['Rör.'], 'Het smörklick.'));
a.push(c('saser', 'sambal-sas', 'Sambal-sås (asiatisk het)', { netto_kh: 2, fett: 0, protein: 1, kcal: 20 }, 5, ['sas', 'asiatisk', 'het'], [{ mangd: 2, enhet: 'msk', vara: 'sambal oelek' }, { mangd: 1, enhet: 'msk', vara: 'soja' }, { mangd: 1, enhet: 'msk', vara: 'limesaft' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }], ['Vispa.'], 'Indonesisk klassiker.'));
a.push(c('saser', 'gochujang-mayo', 'Gochujang-majonnäs', { netto_kh: 2, fett: 18, protein: 1, kcal: 180 }, 4, ['sas', 'koreansk', 'het'], [{ mangd: 2, enhet: 'msk', vara: 'majonnäs' }, { mangd: 1, enhet: 'msk', vara: 'gochujang' }, { mangd: 1, enhet: 'tsk', vara: 'sesamolja' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }], ['Vispa.'], 'Koreansk modern.'));
a.push(c('saser', 'sriracha-majo', 'Sriracha-majo', { netto_kh: 2, fett: 18, protein: 1, kcal: 180 }, 3, ['sas', 'het'], [{ mangd: 2, enhet: 'msk', vara: 'majonnäs' }, { mangd: 1, enhet: 'msk', vara: 'sriracha' }, { mangd: 1, enhet: 'tsk', vara: 'pressad lime' }], ['Vispa.'], 'Snabb het sås.'));
a.push(c('saser', 'caesardressing', 'Caesardressing', { netto_kh: 1, fett: 24, protein: 4, kcal: 240 }, 8, ['sas', 'amerikansk'], [{ mangd: 1, enhet: 'st', vara: 'äggula' }, { mangd: 4, enhet: 'st', vara: 'ansjovisfileer' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'msk', vara: 'dijonsenap' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }, { mangd: 1, enhet: 'dl', vara: 'olivolja' }, { mangd: 30, enhet: 'g', vara: 'parmesan' }], ['Mixa allt.'], 'Klassisk caesar.'));
a.push(c('saser', 'ranchdressing-keto', 'Ranchdressing keto', { netto_kh: 2, fett: 18, protein: 2, kcal: 180 }, 5, ['sas', 'kall', 'amerikansk'], [{ mangd: 1, enhet: 'dl', vara: 'majonnäs' }, { mangd: 1, enhet: 'dl', vara: 'gräddfil' }, { mangd: 1, enhet: 'msk', vara: 'färsk gräslök' }, { mangd: 1, enhet: 'msk', vara: 'färsk persilja' }, { mangd: 1, enhet: 'tsk', vara: 'vitlökspulver' }, 'Salt'], ['Vispa.'], 'Klassisk amerikansk dressing.'));
a.push(c('saser', 'blue-cheese-skipped', '', { netto_kh: 0, fett: 0, protein: 0, kcal: 0 }, 0, [], [], [], '')); // skip blue cheese
a.push(c('saser', 'ailolisas-saffran', 'Saffran-aioli', { netto_kh: 1, fett: 28, protein: 1, kcal: 280 }, 8, ['sas', 'kall', 'spansk'], [{ mangd: 1, enhet: 'st', vara: 'äggula' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1.5, enhet: 'dl', vara: 'olivolja' }, { mangd: 1, enhet: 'krm', vara: 'saffran' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }, 'Salt'], ['Saffran löses i 1 tsk varmt vatten 5 min.', 'Vispa äggula + vitlök, droppa i olja + saffran.'], 'Spanjorsk delikatess.'));
a.push(c('saser', 'chimichurri-rosa', 'Rosa chimichurri', { netto_kh: 1, fett: 18, protein: 1, kcal: 180 }, 8, ['sas', 'sydamerikansk'], [{ mangd: 1, enhet: 'dl', vara: 'färsk persilja' }, { mangd: 0.5, enhet: 'dl', vara: 'färsk oregano' }, { mangd: 1, enhet: 'st', vara: 'röd chili' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'dl', vara: 'olivolja' }, { mangd: 2, enhet: 'msk', vara: 'rödvinsvinäger' }, 'Salt'], ['Hacka, blanda.'], 'Argentinsk klassiker (utan koriander!).'));
a.push(c('saser', 'tahinikram', 'Tahinikram med citron', { netto_kh: 2, fett: 18, protein: 4, kcal: 200 }, 5, ['sas', 'mellanostern'], [{ mangd: 3, enhet: 'msk', vara: 'tahini' }, { mangd: 2, enhet: 'msk', vara: 'pressad citron' }, { mangd: 2, enhet: 'msk', vara: 'kallt vatten' }, { mangd: 1, enhet: 'st', vara: 'vitlöksklyfta' }, 'Salt'], ['Vispa allt.'], 'Mellanöstern-bas-sås.'));
a.push(c('saser', 'gremolata-extra', 'Gremolata med citron', { netto_kh: 1, fett: 10, protein: 1, kcal: 100 }, 8, ['sas', 'italiensk'], [{ mangd: 1, enhet: 'dl', vara: 'färsk persilja' }, { mangd: 2, enhet: 'msk', vara: 'rivet citronskal' }, { mangd: 3, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, 'Flingsalt'], ['Hacka, blanda.'], 'Italiensk fräschet.'));

// === TILLBEHÖR (40) ===
a.push(c('tillbehor', 'rostad-blomkal-cumin', 'Rostad blomkål med cumin', { netto_kh: 4, fett: 14, protein: 4, kcal: 180 }, 35, ['tillbehor', 'gronsak'], [{ mangd: 400, enhet: 'g', vara: 'blomkål, i buketter' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'tsk', vara: 'cumin' }, 'Salt'], ['Blanda blomkål med olja och kryddor.', { namn: 'Ugn', text: '200°C, 25 min.', timer_min: 25 }], 'Mellanösterns blomkål.'));
a.push(c('tillbehor', 'rostad-broccoli-vitlok', 'Rostad broccoli med vitlök', { netto_kh: 4, fett: 12, protein: 4, kcal: 160 }, 22, ['tillbehor', 'gronsak'], [{ mangd: 400, enhet: 'g', vara: 'broccoli, i buketter' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, 'Flingsalt och peppar'], ['Olja, vitlök, salt.', { namn: 'Ugn', text: '220°C, 18 min.', timer_min: 18 }], 'Sprödig vitlöks-broccoli.'));
a.push(c('tillbehor', 'gronkalschips', 'Grönkålschips med flingsalt', { netto_kh: 3, fett: 12, protein: 4, kcal: 150 }, 20, ['tillbehor', 'snack', 'gronsak'], [{ mangd: 200, enhet: 'g', vara: 'grönkål, repad från stjälkar' }, { mangd: 2, enhet: 'msk', vara: 'olivolja' }, 'Flingsalt'], ['Massera kål med olja.', { namn: 'Ugn', text: '160°C, 12 min.', timer_min: 12 }], 'Krispigt sprödbete.'));
a.push(c('tillbehor', 'haricots-verts-mandel', 'Haricots verts med mandel', { netto_kh: 4, fett: 14, protein: 6, kcal: 180 }, 12, ['tillbehor', 'gronsak'], [{ mangd: 300, enhet: 'g', vara: 'haricots verts' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 30, enhet: 'g', vara: 'mandelflakes' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, 'Salt'], ['Stek bönor i smör 5 min.', 'Mandlar och vitlök 2 min.'], 'Klassisk fransk garnityr.'));
a.push(c('tillbehor', 'rostad-rotselleri', 'Rostad rotselleri', { netto_kh: 4, fett: 14, protein: 2, kcal: 170 }, 35, ['tillbehor', 'gronsak'], [{ mangd: 400, enhet: 'g', vara: 'rotselleri, i klyftor' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'msk', vara: 'rosmarin' }, 'Flingsalt'], ['Blanda allt.', { namn: 'Ugn', text: '200°C, 30 min.', timer_min: 30 }], 'Vinter-rotsak.'));
a.push(c('tillbehor', 'rostat-rotselleri-lchf', 'Rotselleri-pommes', { netto_kh: 5, fett: 12, protein: 3, kcal: 170 }, 35, ['tillbehor', 'gronsak'], [{ mangd: 500, enhet: 'g', vara: 'rotselleri, i pommes-strimlor' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'tsk', vara: 'rökt paprika' }, 'Flingsalt'], ['Olja + krydda.', { namn: 'Ugn', text: '220°C, 30 min, vänd halvvägs.', timer_min: 30 }], 'LCHF-pommes.'));
a.push(c('tillbehor', 'rostad-paprika', 'Rostad paprika med olja', { netto_kh: 5, fett: 14, protein: 1, kcal: 170 }, 35, ['tillbehor', 'medelhav'], [{ mangd: 4, enhet: 'st', vara: 'paprikor, i strimlor' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, 'Flingsalt'], ['Olja + vitlök.', { namn: 'Ugn', text: '200°C, 25 min.', timer_min: 25 }], 'Söt rostad paprika.'));
a.push(c('tillbehor', 'rostad-aubergine', 'Rostad aubergine med tahini', { netto_kh: 4, fett: 18, protein: 4, kcal: 220 }, 35, ['tillbehor', 'mellanostern'], [{ mangd: 1, enhet: 'st', vara: 'aubergine' }, { mangd: 2, enhet: 'msk', vara: 'tahini' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, 'Salt'], ['Halvera, gröp, krydda.', { namn: 'Ugn', text: '200°C, 30 min.', timer_min: 30 }, 'Tahini + citron + vitlök över.'], 'Babaganoush.'));
a.push(c('tillbehor', 'guacamole', 'Klassisk guacamole', { netto_kh: 3, fett: 16, protein: 2, kcal: 180 }, 8, ['tillbehor', 'mexikansk'], [{ mangd: 2, enhet: 'st', vara: 'avokado' }, { mangd: 1, enhet: 'st', vara: 'lime' }, { mangd: 0.5, enhet: 'st', vara: 'rödlök' }, { mangd: 1, enhet: 'st', vara: 'jalapeño', notering: 'optional' }, 'Salt'], ['Mosa avokado, blanda allt.'], 'Mexikansk dipping.'));
a.push(c('tillbehor', 'rostad-zucchini-parmesan', 'Rostad zucchini med parmesan', { netto_kh: 3, fett: 14, protein: 6, kcal: 180 }, 22, ['tillbehor', 'italiensk'], [{ mangd: 2, enhet: 'st', vara: 'zucchini, i halvor' }, { mangd: 30, enhet: 'g', vara: 'parmesan, riven' }, { mangd: 2, enhet: 'msk', vara: 'olivolja' }, 'Flingsalt'], ['Olja + parmesan.', { namn: 'Ugn', text: '200°C, 18 min.', timer_min: 18 }], 'Italiensk grönsak.'));
a.push(c('tillbehor', 'fankalstek-rostad', 'Rostad fänkål', { netto_kh: 4, fett: 12, protein: 2, kcal: 150 }, 30, ['tillbehor', 'medelhav'], [{ mangd: 2, enhet: 'st', vara: 'fänkål, i klyftor' }, { mangd: 3, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'tsk', vara: 'fänkålsfrö' }, 'Flingsalt'], ['Olja + frön + salt.', { namn: 'Ugn', text: '200°C, 25 min.', timer_min: 25 }], 'Sötgrönsak.'));
a.push(c('tillbehor', 'spenat-pinjenotter', 'Smörstekt spenat med pinjenötter', { netto_kh: 2, fett: 16, protein: 6, kcal: 180 }, 8, ['tillbehor', 'gronsak'], [{ mangd: 400, enhet: 'g', vara: 'spenat' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 30, enhet: 'g', vara: 'pinjenötter' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }], ['Stek pinjenötter torrt 1 min.', 'Smör + vitlök + spenat 3 min.'], 'Italiensk garnityr.'));
a.push(c('tillbehor', 'krasna-rostade-tomater', 'Rostade körsbärstomater', { netto_kh: 3, fett: 10, protein: 1, kcal: 120 }, 20, ['tillbehor', 'snabb'], [{ mangd: 300, enhet: 'g', vara: 'körsbärstomater' }, { mangd: 2, enhet: 'msk', vara: 'olivolja' }, { mangd: 4, enhet: 'st', vara: 'vitlöksklyftor' }, 'Flingsalt, basilika'], [{ namn: 'Ugn', text: '180°C, 18 min.', timer_min: 18 }], 'Snabb sida.'));
a.push(c('tillbehor', 'haloumi-stek', 'Stekt halloumi i citron', { netto_kh: 2, fett: 22, protein: 18, kcal: 280 }, 8, ['tillbehor', 'mellanostern', 'snabb'], [{ mangd: 200, enhet: 'g', vara: 'halloumi, i skivor' }, { mangd: 1, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'st', vara: 'citron' }, { mangd: 1, enhet: 'krm', vara: 'oregano' }], ['Stek halloumi 2 min/sida.', 'Citronsaft + oregano.'], 'Vegetariskt protein.'));
a.push(c('tillbehor', 'koreanska-grokalchips', 'Korean grönkålschips', { netto_kh: 3, fett: 14, protein: 5, kcal: 170 }, 22, ['tillbehor', 'koreansk', 'snack'], [{ mangd: 200, enhet: 'g', vara: 'grönkål' }, { mangd: 2, enhet: 'msk', vara: 'sesamolja' }, { mangd: 1, enhet: 'msk', vara: 'sesamfrön' }, { mangd: 1, enhet: 'tsk', vara: 'gochujang' }], ['Massera kål med olja + gochujang.', { namn: 'Ugn', text: '160°C, 15 min.', timer_min: 15 }], 'Koreansk twist.'));
a.push(c('tillbehor', 'asiatisk-kål-snabb', 'Asiatisk kålwok', { netfo_kh: 3, fett: 12, protein: 3, kcal: 140 }, 8, ['tillbehor', 'asiatisk', 'snabb'], [{ mangd: 400, enhet: 'g', vara: 'savojkål, strimlad' }, { mangd: 1, enhet: 'msk', vara: 'sesamolja' }, { mangd: 1, enhet: 'msk', vara: 'soja' }, { mangd: 1, enhet: 'tsk', vara: 'rivet ingefära' }], ['Wokra hög värme 5 min.'], 'Snabb asiatisk.'));

// === SALLADER (extra) ===
a.push(c('sallader', 'spinat-feta-grek', 'Grek-spenat-fetaost-sallad', { netto_kh: 4, fett: 18, protein: 8, kcal: 240 }, 8, ['sallad', 'medelhav'], [{ mangd: 200, enhet: 'g', vara: 'baby-spenat' }, { mangd: 100, enhet: 'g', vara: 'fetaost' }, { mangd: 50, enhet: 'g', vara: 'kalamata-oliver' }, { mangd: 1, enhet: 'st', vara: 'rödlök' }, { mangd: 2, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'msk', vara: 'rödvinsvinäger' }], ['Blanda allt.'], 'Grek-medel-sallad.'));
a.push(c('sallader', 'kyckling-sesam-sallad', 'Sesam-kycklingsallad asiatisk', { netto_kh: 4, fett: 22, protein: 30, kcal: 360 }, 15, ['sallad', 'asiatisk', 'kyckling'], [{ mangd: 300, enhet: 'g', vara: 'kyckling, kokt och strimlad' }, { mangd: 200, enhet: 'g', vara: 'kinakål' }, { mangd: 1, enhet: 'st', vara: 'gurka' }, { mangd: 1, enhet: 'msk', vara: 'sesamfrön' }, { mangd: 2, enhet: 'msk', vara: 'soja' }, { mangd: 2, enhet: 'msk', vara: 'sesamolja' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }], ['Blanda dressing.', 'Häll över.'], 'Sesam-asiatisk.'));
a.push(c('sallader', 'ankastromad-orientalisk', 'Anka-sallad med apelsin (LCHF)', { netto_kh: 5, fett: 24, protein: 28, kcal: 380 }, 18, ['sallad', 'asiatisk', 'anka'], [{ mangd: 300, enhet: 'g', vara: 'anka, stekt och skuren' }, { mangd: 200, enhet: 'g', vara: 'sallad' }, { mangd: 1, enhet: 'msk', vara: 'rivet apelsinskal' }, { mangd: 2, enhet: 'msk', vara: 'soja' }, { mangd: 1, enhet: 'msk', vara: 'sesamolja' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }], ['Blanda dressing utan apelsinjuice.', 'Anka över sallad.'], 'Asiatisk anka.'));
a.push(c('sallader', 'tonfisk-medelhav-bowl', 'Tonfisk-medelhavs-bowl', { netto_kh: 4, fett: 22, protein: 26, kcal: 340 }, 10, ['sallad', 'medelhav', 'fisk'], [{ mangd: 200, enhet: 'g', vara: 'tonfisk i olja' }, { mangd: 100, enhet: 'g', vara: 'gurka' }, { mangd: 100, enhet: 'g', vara: 'tomat' }, { mangd: 50, enhet: 'g', vara: 'fetaost' }, { mangd: 30, enhet: 'g', vara: 'kalamata-oliver' }, { mangd: 1, enhet: 'msk', vara: 'olivolja' }, { mangd: 1, enhet: 'msk', vara: 'pressad citron' }], ['Blanda.'], 'Snabb medelhavs-lunch.'));
a.push(c('sallader', 'lammkebab-grek', 'Lammkebab på grek-sallad', { netto_kh: 5, fett: 28, protein: 28, kcal: 410 }, 25, ['sallad', 'medelhav', 'lamm'], [{ mangd: 300, enhet: 'g', vara: 'lammkebab' }, { mangd: 200, enhet: 'g', vara: 'sallad' }, { mangd: 1, enhet: 'st', vara: 'gurka' }, { mangd: 100, enhet: 'g', vara: 'tomat' }, { mangd: 50, enhet: 'g', vara: 'fetaost' }, { mangd: 1, enhet: 'msk', vara: 'olivolja' }, 'Tzatziki'], ['Stek lammkebab 8 min.', 'Anrätta över sallad.'], 'Grekisk lammbowl.'));
a.push(c('sallader', 'spaghetti-zucchini-pesto', 'Zucchini-spaghetti pesto', { netto_kh: 4, fett: 22, protein: 8, kcal: 280 }, 12, ['sallad', 'lunch', 'italiensk'], [{ mangd: 2, enhet: 'st', vara: 'zucchini, spiraliserade' }, { mangd: 3, enhet: 'msk', vara: 'pesto' }, { mangd: 30, enhet: 'g', vara: 'parmesan' }, { mangd: 30, enhet: 'g', vara: 'pinjenötter' }, 'Färsk basilika'], ['Wokra zoodles 2 min.', 'Pesto + parmesan + pinjenötter.'], 'Italiensk LCHF-lunch.'));

// === PROTEINER (extra) ===
a.push(c('proteiner', 'lammbog-stekt-tunnt', 'Lammbog tunnt-stekt', { netto_kh: 0, fett: 28, protein: 32, kcal: 380 }, 12, ['lamm'], [{ mangd: 400, enhet: 'g', vara: 'lammbog, i tunna skivor' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Rosmarin', 'Salt och peppar'], ['Stek 3 min/sida.'], 'Snabbt lamm.'));
a.push(c('proteiner', 'kalv-tartar', 'Kalv-tartar', { netto_kh: 1, fett: 14, protein: 28, kcal: 240 }, 12, ['kalv', 'rakott', 'lyx'], [{ mangd: 200, enhet: 'g', vara: 'kalvfilé, finhackad' }, { mangd: 1, enhet: 'st', vara: 'äggula' }, { mangd: 1, enhet: 'msk', vara: 'rödlök' }, { mangd: 1, enhet: 'tsk', vara: 'kapris' }, 'Salt'], ['Blanda allt utom äggula.', 'Forma, gula i mitten.'], 'Mildare än oxtartar.'));
a.push(c('proteiner', 'salt-fläsksida-baktad', 'Saltbakad fläsksida', { netto_kh: 0, fett: 38, protein: 28, kcal: 460 }, 90, ['flask', 'helg'], [{ mangd: 800, enhet: 'g', vara: 'fläsksida' }, { mangd: 200, enhet: 'g', vara: 'flingsalt' }, 'Svartpepparkorn'], ['Krysstrissa svålen.', 'Täck med salt.', { namn: 'Ugn', text: '180°C, 75 min.', timer_min: 75 }], 'Saltbakad — förvånansvärt bra.'));
a.push(c('proteiner', 'lammkorv-hemmagjord', 'Hemmagjord lammkorv', { netto_kh: 1, fett: 28, protein: 24, kcal: 360 }, 25, ['lamm', 'kottfars'], [{ mangd: 500, enhet: 'g', vara: 'lammfärs' }, { mangd: 1, enhet: 'tsk', vara: 'cumin' }, { mangd: 1, enhet: 'tsk', vara: 'cayenne' }, { mangd: 2, enhet: 'st', vara: 'vitlöksklyftor' }, { mangd: 1, enhet: 'tsk', vara: 'paprika' }, 'Salt'], ['Blanda, forma till korv-form.', 'Stek 8 min/sida.'], 'Lammkorv hemma.'));

// === BASER (extra) ===
a.push(c('baser', 'savoy-vitkalsmix', 'Savoy-vitkålsmix', { netto_kh: 4, fett: 16, protein: 3, kcal: 180 }, 12, ['bas', 'gronsak'], [{ mangd: 200, enhet: 'g', vara: 'savojkål' }, { mangd: 200, enhet: 'g', vara: 'vitkål' }, { mangd: 30, enhet: 'g', vara: 'smör' }, 'Salt'], [{ namn: 'Stek', text: '10 min.', timer_min: 10 }], 'Mix-bas.'));
a.push(c('baser', 'broccolimos-cheddar', 'Broccolimos med cheddar', { netto_kh: 5, fett: 22, protein: 10, kcal: 280 }, 18, ['bas', 'krammig'], [{ mangd: 400, enhet: 'g', vara: 'broccoli' }, { mangd: 50, enhet: 'g', vara: 'cheddar' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 0.5, enhet: 'dl', vara: 'grädde' }], ['Koka, mosa med ost + smör + grädde.'], 'Krämigare broccolimos.'));
a.push(c('baser', 'haricots-grä-kokt', 'Haricots verts kokta i smör', { netto_kh: 4, fett: 16, protein: 4, kcal: 180 }, 8, ['bas', 'snabb'], [{ mangd: 400, enhet: 'g', vara: 'haricots verts' }, { mangd: 40, enhet: 'g', vara: 'smör' }, 'Flingsalt'], [{ namn: 'Sjud', text: 'I lite vatten + smör 6 min.', timer_min: 6 }], 'Snabb sida.'));

// === SOPPOR (extra) ===
a.push(c('soppor', 'fransk-loksoppa', 'Fransk löksoppa LCHF', { netto_kh: 5, fett: 22, protein: 18, kcal: 320 }, 50, ['soppa', 'fransk', 'helg'], [{ mangd: 4, enhet: 'st', vara: 'gula lökar, strimlade' }, { mangd: 50, enhet: 'g', vara: 'smör' }, { mangd: 1, enhet: 'liter', vara: 'kötbuljong' }, { mangd: 1, enhet: 'dl', vara: 'torrt rödvin' }, { mangd: 100, enhet: 'g', vara: 'gruyère, riven' }, 'Färsk timjan'], ['Karamellisera lök i smör 30 min.', 'Vin + buljong + timjan, sjud 15 min.', 'Riv ost över, gratinera 5 min.'], 'Fransk klassiker.'));
a.push(c('soppor', 'fransk-fisksoppa-bouillabaisse', 'Bouillabaisse', { netto_kh: 4, fett: 18, protein: 24, kcal: 280 }, 45, ['soppa', 'fransk', 'fisk'], [{ mangd: 600, enhet: 'g', vara: 'blandad fisk' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 1, enhet: 'st', vara: 'fänkål' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 1, enhet: 'krm', vara: 'saffran' }, { mangd: 5, enhet: 'dl', vara: 'fiskbuljong' }, 'Vitvin, vitlök'], ['Stek lök + fänkål 5 min.', 'Tomat + saffran + buljong + vin, sjud 15 min.', 'Fisk sista 8 min.'], 'Marseille-klassiker.'));
a.push(c('soppor', 'gulash-soppa', 'Ungersk gulashsoppa', { netto_kh: 5, fett: 22, protein: 28, kcal: 350 }, 90, ['soppa', 'ungersk', 'helg'], [{ mangd: 500, enhet: 'g', vara: 'gryt-kött' }, { mangd: 1, enhet: 'st', vara: 'lök' }, { mangd: 2, enhet: 'msk', vara: 'paprikapulver' }, { mangd: 1, enhet: 'tsk', vara: 'cumin' }, { mangd: 5, enhet: 'dl', vara: 'kötbuljong' }, { mangd: 200, enhet: 'g', vara: 'krossade tomater' }, { mangd: 30, enhet: 'g', vara: 'smör' }], ['Bryn kött 5 min.', 'Lök + paprika + cumin 2 min.', 'Buljong + tomat, sjud 75 min.'], 'Stark soppa.'));
a.push(c('soppor', 'asiatisk-laksa', 'Asiatisk laksa-soppa', { netto_kh: 5, fett: 24, protein: 22, kcal: 340 }, 25, ['soppa', 'asiatisk'], [{ mangd: 400, enhet: 'g', vara: 'kyckling eller räkor' }, { mangd: 4, enhet: 'dl', vara: 'kokosmjölk' }, { mangd: 2, enhet: 'msk', vara: 'thai röd curry' }, { mangd: 2, enhet: 'dl', vara: 'kycklingbuljong' }, { mangd: 1, enhet: 'st', vara: 'lime' }, 'Thaibasilika'], ['Bryn curry 2 min.', 'Kokosmjölk + buljong, sjud 10 min.', 'Protein 5 min.', 'Lime + basilika.'], 'Sydostasiatisk-fusion.'));

// === FRUKOST (extra) ===
a.push(c('frukost', 'feta-tomat-omelett', 'Feta-tomat-omelett', { netto_kh: 3, fett: 28, protein: 22, kcal: 360 }, 9, ['frukost', 'medelhav'], [{ mangd: 3, enhet: 'st', vara: 'ägg' }, { mangd: 50, enhet: 'g', vara: 'fetaost' }, { mangd: 100, enhet: 'g', vara: 'körsbärstomater' }, { mangd: 20, enhet: 'g', vara: 'smör' }], ['Stek tomater 1 min.', 'Häll i ägg, fetaost. Vik.'], 'Mediterran omelett.'));
a.push(c('frukost', 'gröna-äggröra', 'Grön äggröra med spenat', { netto_kh: 2, fett: 24, protein: 22, kcal: 320 }, 7, ['frukost', 'agg'], [{ mangd: 4, enhet: 'st', vara: 'ägg' }, { mangd: 100, enhet: 'g', vara: 'baby-spenat' }, { mangd: 30, enhet: 'g', vara: 'smör' }, { mangd: 30, enhet: 'g', vara: 'parmesan' }], ['Stek spenat 1 min.', 'Vispade ägg, rör mjukt 3 min.', 'Parmesan över.'], 'Grön start.'));
a.push(c('frukost', 'protein-pannkakor', 'Protein-pannkakor', { netto_kh: 4, fett: 18, protein: 28, kcal: 320 }, 15, ['frukost', 'protein'], [{ mangd: 4, enhet: 'st', vara: 'ägg' }, { mangd: 30, enhet: 'g', vara: 'vassleprotein vanilj' }, { mangd: 50, enhet: 'g', vara: 'mandelmjöl' }, { mangd: 1, enhet: 'tsk', vara: 'bakpulver' }, { mangd: 30, enhet: 'g', vara: 'smör' }], ['Mixa, stek pannkakor 1 min/sida.'], 'Hög protein.'));
a.push(c('frukost', 'overnight-chia-vanilj', 'Overnight chia med vanilj', { netto_kh: 4, fett: 18, protein: 6, kcal: 220 }, 5, ['frukost', 'kall', 'forberedd'], [{ mangd: 3, enhet: 'msk', vara: 'chiafrön' }, { mangd: 2, enhet: 'dl', vara: 'mandelmjölk' }, { mangd: 1, enhet: 'tsk', vara: 'vaniljextrakt' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }, { mangd: 1, enhet: 'msk', vara: 'kokosflakes' }], ['Blanda, kyl över natten.'], 'Förbered kvällen innan.'));

// === EFTERRÄTTER (extra) ===
a.push(c('efterratter', 'jordgubbschia-pudding', 'Jordgubbschia-pudding', { netto_kh: 5, fett: 18, protein: 6, kcal: 220 }, 5, ['efterratt'], [{ mangd: 3, enhet: 'msk', vara: 'chiafrön' }, { mangd: 2, enhet: 'dl', vara: 'kokosmjölk' }, { mangd: 50, enhet: 'g', vara: 'jordgubbar, mosade' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }], ['Blanda, kyl 4 tim.'], 'Sommar-pudding.'));
a.push(c('efterratter', 'mascarpone-bar-bowl', 'Mascarpone-bär-bowl', { netto_kh: 4, fett: 28, protein: 6, kcal: 320 }, 8, ['efterratt'], [{ mangd: 200, enhet: 'g', vara: 'mascarpone' }, { mangd: 1, enhet: 'dl', vara: 'vispgrädde' }, { mangd: 50, enhet: 'g', vara: 'hallon' }, { mangd: 1, enhet: 'tsk', vara: 'erytritol' }, { mangd: 1, enhet: 'tsk', vara: 'vaniljextrakt' }], ['Vispa mascarpone + grädde + erytritol.', 'Topp med hallon.'], 'Snabb italiensk.'));
a.push(c('efterratter', 'choklad-fudge-keto', 'Choklad-fudge keto', { netto_kh: 3, fett: 24, protein: 4, kcal: 270 }, 60, ['efterratt', 'choklad'], [{ mangd: 100, enhet: 'g', vara: '85% mörk choklad' }, { mangd: 100, enhet: 'g', vara: 'kokosolja' }, { mangd: 50, enhet: 'g', vara: 'mandelsmör' }, { mangd: 30, enhet: 'g', vara: 'erytritol' }], ['Smält allt.', 'Häll i form, kyl 1 tim.'], 'LCHF-godis.'));
a.push(c('efterratter', 'kokosbollar-rom', 'Kokosbollar med rom', { netto_kh: 3, fett: 22, protein: 3, kcal: 250 }, 20, ['efterratt'], [{ mangd: 100, enhet: 'g', vara: 'riven kokos' }, { mangd: 50, enhet: 'g', vara: 'smör, smält' }, { mangd: 30, enhet: 'g', vara: 'erytritol' }, { mangd: 1, enhet: 'msk', vara: 'rom-extrakt' }], ['Blanda, forma 8 bollar, kyl.'], 'Klassisk svensk.'));
a.push(c('efterratter', 'fudge-jordnotssmor', 'Jordnötssmör-fudge', { netto_kh: 3, fett: 22, protein: 8, kcal: 280 }, 60, ['efterratt'], [{ mangd: 100, enhet: 'g', vara: 'jordnötssmör' }, { mangd: 50, enhet: 'g', vara: 'kokosolja' }, { mangd: 30, enhet: 'g', vara: 'erytritol' }, { mangd: 1, enhet: 'tsk', vara: 'vaniljextrakt' }], ['Värm smällt.', 'Häll i form, kyl 1 tim.'], 'Amerikansk klassiker.'));

// === SNACKS (extra) ===
a.push(c('snacks', 'salami-rullar-cream-cheese', 'Salami-rullar med gräddost', { netto_kh: 1, fett: 22, protein: 14, kcal: 260 }, 5, ['snack'], [{ mangd: 100, enhet: 'g', vara: 'salami, i skivor' }, { mangd: 100, enhet: 'g', vara: 'gräddost' }, { mangd: 1, enhet: 'msk', vara: 'färsk gräslök' }], ['Bred gräddost + gräslök på salami, rulla.'], 'Snack i 5 min.'));
a.push(c('snacks', 'cucumber-rolls-fishtartare', 'Gurkrullar med tonfisktartare', { netto_kh: 2, fett: 14, protein: 16, kcal: 220 }, 12, ['snack', 'fisk'], [{ mangd: 1, enhet: 'st', vara: 'gurka, tunna skivor' }, { mangd: 200, enhet: 'g', vara: 'tonfisk' }, { mangd: 1, enhet: 'msk', vara: 'majonnäs' }, { mangd: 1, enhet: 'msk', vara: 'soja' }], ['Hacka tonfisk, blanda med majo + soja.', 'Lägg på gurkskivor, rulla.'], 'Sushi-stil-snack.'));
a.push(c('snacks', 'fattburgare-utan-bun', 'Mini-burgare utan bun', { netto_kh: 1, fett: 22, protein: 18, kcal: 280 }, 12, ['snack'], [{ mangd: 200, enhet: 'g', vara: 'nötfärs' }, { mangd: 4, enhet: 'skivor', vara: 'cheddar' }, { mangd: 4, enhet: 'salladsblad' }, 'Salt, peppar, senap'], ['Forma 4 mini-bullar, stek 3 min/sida.', 'Smält ost.', 'Lägg i salladsblad.'], 'Burger-snack.'));

const filtered = a.filter((r) => r.namn && r.taggar && r.taggar.length > 0);
const byModul = {};
for (const r of filtered) {
  const m = r.modul;
  delete r.modul;
  if (!byModul[m]) byModul[m] = [];
  byModul[m].push(r);
}
let total = 0;
for (const [m, rs] of Object.entries(byModul)) {
  const result = bulkSkriv(m, rs);
  console.log(`${m}: ${result.written} (${result.skipped} hoppade över)`);
  total += result.written;
}
console.log(`\nTotal: ${total}`);
